### ISSUE TITLE
@Loader decorator broken with new NestJS release (v7)

### ISSUE THREAD

**Issue by kylejreed** [krislefeber/nestjs-dataloader#16]
The method signature for "createParamDecorator" changed in the new release of NestJS. I believe it should now be:

`export const Loader = createParamDecorator((data: string, ctx: ExecutionContext) => {
  const context = GqlExecutionContext.create(ctx).getContext()
//rest of functionality using this context
});
`

**Comment by babbarankit** [comment]
@kylejreed Thanks 👍

**Comment by jakeblaxon** [comment]
Any followup with this?

**Comment by brianschardt** [comment]
Any updates on this?
