### ISSUE TITLE
Example of usage with ResolveProperty decodator

### ISSUE THREAD

**Issue by vorant94** [krislefeber/nestjs-dataloader#21]
Hello there, I am new to GraphQL and have found a good way to use it along with NestJS library. I've used it a little and stuck with this N+1 problem, when after a couple of child nodes one query may cause a hundred calls to DB or whatever. I asked at forums and so on to find a solution and was advised to try your library. I am not sure that my question is really worth opening an issue here, but it is the only easy way I have to communicate with you, so... long story short here is my question

In your README example you showed usage of Loader decorator on a function with a Query decorator, so I can query multiple Accounts with a single call. But in my case I have something like that:
I have Account, each Account have many Subscribers (via ResolveProperty decorated function), each Subscriber have many NetworkResources and some other data (each one via ResolveProperty decorated function)

When I make a full query of one Account NestJS will make:
1 request to get Account itself
1 request to get all Subscribers by this Account id
1 request per each Subscriber it got from previous step to get NetworkResources by this Subscriber id
1 request per each other Subscriber ResolveProperty function

Assume each Account has 5 Subscribers, query to get one Accoount will cause 1 + 1 + 5 + ... requests. If I request for example 3 Accounts query will cause 1 + 3 + 3 * 5 + ... requests. All this water-falling is caused by the fact that ResolveProperty decorator works separately for each Subscriber instance even when I request several Subscribers.

Does your library allow to somehow have ResolveProperty decorator to get all NetworkResources of all 15 Subscribers from my example with one request and after it group them by its Subscriber? If yes, can you provide some example? If not can you advise some other solution that may fit my problem?

**Comment by krislefeber** [comment]
Hi @vorant94, the data loader api is really designed for one to one mappings, and not one to many mappings like you have. Is the request you are making only needing to know about the NetworkResources? If so, I would suggest writing a specific query for your data store(SQL if you are using a relational database) that allows you to pass in the account and get a paginated list of NetworkResources.
