### ISSUE TITLE
Quick Question Job offer

### ISSUE THREAD

**Issue by brianschardt** [krislefeber/nestjs-dataloader#48]
I am the founder of a well funded VC-backed social stock app called Iris. We allow our users to connect their Robinhood or other broker to our platform so they can share their trades with their friends and family real-time. 

We are looking to expand our backend team, we use nestjs, graphql etc. Are you open to hoping on a call for 30 min?

**Comment by krislefeber** [comment]
Hi Brian,

I'm not actively looking for employment at this time, but I may be able to
offer some assistance.

Feel free to give me a call at 1-920-979-4386 as I am interested in
learning more.

Thanks,
Kris

**Comment by brianschardt** [comment]
Tried to call that number, what’s the best time to reach you?

**Comment by krislefeber** [comment]
Sorry, there was a typo. It's 920-979-4836. I'm free all day today.
