### ISSUE TITLE
Property generateDataLoader in type 'Loader'  is not assignable to the same property in base type 'NestDataLoader<number,'Entity'>.

### ISSUE THREAD

**Issue by Webhst** [krislefeber/nestjs-dataloader#6]
Hi, I'm going through a problem with the methods generateDataLoader() in NestDataLoader

This is the code 

import * as DataLoader from 'dataloader';
import { Injectable } from '@nestjs/common';
import { NestDataLoader } from 'nestjs-dataloader';
import { Entity } from '../../shared/entities/';
import { In } from 'typeorm';

@Injectable()
export class Loader implements NestDataLoader <number, Entity> {

  generateDataLoader(): DataLoader<number, Entity> {
    return new DataLoader<number, Entity>(keys => this.findByKeys(keys));
  }
  
  private async findByKeys( keys: number[]) {
      const accounts = await Entity.find( {entityKey:  In(keys)}  );
      const result = keys.map(key => accounts.filter((account) => account.entityKey === key));
      return result;
  }
}

The error is as follows if i over the method generateDataLoader()
and in the parameter keys on method (findByKeys)

(method) Loader.generateDataLoader(): DataLoader<number, Entity, number>
Should return a new instance of dataloader each time

Property 'generateDataLoader' in type 'Loader' is not assignable to the same property in base type 'NestDataLoader<number, Entity>'.
  Type '() => DataLoader<number, Entity, number>' is not assignable to type '() => DataLoader<number, Entity>'.
    Type 'DataLoader<number, Entity, number>' is not assignable to type 'DataLoader<number, Entity>'.
      Types of property 'loadMany' are incompatible.
        Type '(keys: ArrayLike<number>) => Promise<(Entity | Error)[]>' is not assignable to type '(keys: number[]) => Promise<Entity>'.
          Type 'Promise<(Entity | Error)[]>' is not assignable to type 'Promise<Entity>'.
            Type '(Entity | Error)[]' is not assignable to type 'Entity'.
              Type 'Entity | Error' is not assignable to type 'Entity'.
                Type 'Error' is missing the following properties from type 'Entity': length, pop, push, concat, and 28 more.ts(2416)

Also after run npm install i get this error , I m on Windows 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\nestjs-dataloader\node_modules\fsevents): It has something to do?

can somebody help me with this please ?

**Comment by schardtbc** [comment]
@Injectable()
export class Loader implements NestDataLoader <number, Entity[]> {

generateDataLoader(): DataLoader<number, Entity[]> {
return new DataLoader<number, Entity[]>(keys => this.findByKeys(keys));
}

would fix the type errors but I don't believe that does what you want as the return result from findByKeys is now an Entity[][].

**Comment by schardtbc** [comment]
private async findByKeys( keys: number[]) {
const accounts = await Entity.find( {entityKey: In(keys)} );
const result = keys.map(key => accounts.filter((account) => account.entityKey === key));
return result;
}
}

the function as written returns an Entity[][]

private async findByKeys( keys: number[]) {
const entities = await Entity.find( {entityKey: In(keys)} );
const result = keys.map(key => entities.filter((entity) => entity.entityKey === key)[0]);
return result;
}
}

this will return an Entity[] and will work as long as the entityKey is the primary key for the entity, in which case the Entity.find call will only return one result per key.

**Comment by schardtbc** [comment]
"Also after run npm install i get this error , I m on Windows

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\nestjs-dataloader\node_modules\fsevents): It has something to do?"

this warning is probably inconsequential.

**Comment by Webhst** [comment]
Thank you for your answer @schardtbc , I still getting the same error even when i do that , i dont think that can be a problem with the operative system isnt it?

**Comment by Webhst** [comment]
the method in return new DataLoader<number, Entity>(keys => this.findByKeys(keys)); is showing an error like Argument of type 'readonly number[]' is not assignable to parameter of type 'number[]'.                
Type 'readonly number[]' is missing the following properties from type 'number[]': pop,push,reverse,shift and 6 more. 

does that have something to do with the problem of function ?

**Comment by schardtbc** [comment]
can you create an issue on prototype-two and I can investigate from there?

**Comment by krislefeber** [comment]
> the method in return new DataLoader<number, Entity>(keys => this.findByKeys(keys)); is showing an error like Argument of type 'readonly number[]' is not assignable to parameter of type 'number[]'.
Type 'readonly number[]' is missing the following properties from type 'number[]': pop,push,reverse,shift and 6 more.
@Webhst, this is most likely the result of your types not matching up between your data layer and the dataloader function. Please provide a gist with the full NestDataloader implementation and the function that it is calling for findByKeys

**Comment by Webhst** [comment]
Thank for your answer @krislefeber , this was resolved i had problem with version type.
