### ISSUE TITLE
Upgrade to dataloader v2

### ISSUE THREAD

**Issue by 0b10** [krislefeber/nestjs-dataloader#7]
The interface differs slightly, for instance loadMany() has a return type of `Array<V | Error>`, but only `Array<V>` in v1.4.

**Comment by krislefeber** [comment]
Can you provide a code sample? I'm not sure I follow. Is this an issue in this library or the dataloader library?

**Comment by 0b10** [comment]
dataloader v2: https://github.com/graphql/dataloader/releases/tag/v2.0.0
dataloader user in this project: https://github.com/krislefeber/nestjs-dataloader/blob/41e3baccccdf50405c8ab70c9310795028d09c44/package.json#L17

Forgive me if I misunderstand, but doesn't ^1.x only include compatible version - e.g. same major version number - 1.x. Installing this lib pulls in v1.x.

v2 has some minor interface changes.

**Comment by krislefeber** [comment]
This project isn't up to date with the latest version of dataloader. Feel free to submit a PR, otherwise I will try to get to it when I have time.

**Comment by 0b10** [comment]
Sure, I'll have a look if I continue to use this library.
